#!/usr/bin/env python
# coding: utf-8

# # New Vaginal Ointement: pH-m3 
# 
# ## Gelatin-based pH-balancing Ointment
# 
# ### Data Analysis
# 
# In this section the user will:
# 
# - Download the dataset,
# - Anaylse the data,
# - Preprocess the data,
# - Apply a machine learning model.

# In[9]:


import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


df = pd.DataFrame(np.random.randn(1000, 2), columns=["a", "b"])

df["b"] = df["b"] + np.arange(1000)

df.plot.hexbin(x="a", y="b", gridsize=25);

#Designated pH levels range from 0-10 pH due to testing of different diseases/infections
#within the vulva. This figure represents a model for the test range. 


# # Collection of Data
# 
# ## Logistics of collection 
# 
# pH for each ointement was primarily tested for change in pH when mixed for 10 minutes with a unbalenced (liquid) substance. All pH samples were 
# 10 mL and substance samples were ~15 mL. 
# 
# Change in pH was calculated via [percentage] difference. 
# #pH via (new) application methodology: 10 mL of the respective substance were placed on the gusset, then an subsequent unbalenced pH liquid was placed on the areas around (12.5 circumference). External (consistent) temperature: 71°F. Waited ~10 minutes to average pH based on results derived from Logger Lite.© 
# 
# Melting point: 10 mL of each solution, temperature (external): 71°F.=, 10 mL of each substance in solidified form. As soon as the substance melted at the bottom of the substances' (polyethylene) container, it was logged as the 'melting point' for the respective substance.

# In[20]:


import pandas as pd
import numpy as np 


# In[ ]:


pH	Change in pH	pH via application model	Change in pH
Pre-term birth [pH: 7] 		4.67	66.70%	4.63	66.10%
Menopause [pH: 6.5]		4.15	63.80%	4.2	64.60%
Trichomoniasis [pH: 6]		4.56	76%	4.53	76%
Douching Vagina [pH: 5.5] 		4.8	87.30%	4.77	87.30%
Bacterial Vaginosis [pH: 5]		4.34	86.80%	4.32	86.80%
High lactobacillus [pH: 3] 		4.53	66.20%	4.5	66.20%
					
					
					
					
Melting point [simulation for vaginal heat]:					
	Starting Temperature (C) 	Temperature (F) 	Temperature (C)	Melting Point (seconds) 	
Trial 1. 	17.5°C	90.5 °F	32.5°C	50	
Trial 2. 	17.3°C	92.5 °F	33.6°C	44	
Trial 3. 	17.4°C	93.5 °F	34°C	40	
Trial 4. 	17.4°C	95.5 °F	35°C	38	
Trial 5. 	17.2°C	100.5 °F	37.8°C	15	


# In[30]:


data = pd.read_csv("SRA - Sheet1.csv")
print("Data read sucessfully")
print(data)


# ## Run code to view data chart [Solution a]
# ![chart%20%281%29.png](attachment:chart%20%281%29.png)

# In[ ]:


pH	Change in pH	pH via application model	Change in pH
Pre-term birth [pH: 7] 		4.88	69.70%	4.85	69.30%
Menopause [pH: 6.5]		4.8	73.80%	4.79	73.70%
Trichomoniasis [pH: 6]		4.43	74%	4.42	74%
Douching Vagina [pH: 5.5] 		4.27	77.60%	4.25	77.30%
Bacterial Vaginosis [pH: 5]		4.06	81.20%	4.03	80.60%
High lactobacillus [pH: 3] 		3.96	75.80%	3.94	76.10%
			
			
			
			
Melting point [simulation for vaginal heat]:					
	Starting Temperature (C) 	Temperature (F) 	Temperature (C)	Melting Point (seconds) 	
Trial 1. 	18.6°C	90.5 °F	32.5°C	37	
Trial 2. 	18.9°C	92.5 °F	33.6°C	35	
Trial 3. 	17.8°C	93.5 °F	34°C	32	
Trial 4. 	19.1°C	95.5 °F	35°C	27	
Trial 5. 	19°C	100.5 °F	37.8°C	25	


# In[31]:


data = pd.read_csv("SRB - Sheet1.csv")
print("Data read sucessfully")
print(data)


# ## Run code to view data chart [Solution b]
# 
# ![chart%20%282%29.png](attachment:chart%20%282%29.png)

# In[ ]:


pH	Change in pH	pH via application model	Change in pH
Pre-term birth [pH: 7] 		4.7	67.10%	4.71	67.30%
Menopause [pH: 6.5]		4.43	68.20%	4.45	68.50%
Trichomoniasis [pH: 6]		4.52	75%	4.54	76%
Douching Vagina [pH: 5.5] 		4.71	85.60%	4.73	86.00%
Bacterial Vaginosis [pH: 5]		4.54	90.80%	4.56	91.20%
High lactobacillus [pH: 3] 		4.62	154.00%	4.65	64.50%
			
			
			
			
Melting point [simulation for vaginal heat]:					
	Starting Temperature (C) 	Temperature (F) 	Temperature (C)	Melting Point (seconds) 	
Trial 1. 	18.7°C	90.5 °F	32°C	36	
Trial 2. 	18.5°C	92.5 °F	33.6°C	30	
Trial 3. 	18.6°C	93.5 °F	34°C	27	
Trial 4. 	18.9°C	95.5 °F	35°C	25	
Trial 5. 	18.2°C	100.5 °F	37.8°C	14	


# In[32]:


data = pd.read_csv("SRC - Sheet1.csv")
print("Data read sucessfully")
print(data)


# ## Run code to view data chart [Solution c]
# 
# ![chart%20%283%29.png](attachment:chart%20%283%29.png)
